/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controller;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Ly Tinh Nhiem
 */
public class MenuPanel2 extends javax.swing.JPanel {

    private boolean hovered = false;

    public MenuPanel2() {
        initComponents();
    }

    // Phương thức để thiết lập trạng thái hover
    public void setHovered(boolean hovered) {
        this.hovered = hovered;
        repaint(); // Khi trạng thái hover thay đổi, vẽ lại panel để áp dụng hiệu ứng
    }
    

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (hovered) {
            // Vẽ background hoặc áp dụng hiệu ứng hover tùy thuộc vào ý muốn của bạn
            g.setColor(new Color(100, 100, 100));
            g.fillRect(0, 0, getWidth(), getHeight());
        }
        // Các mã vẽ khác ở đây
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clbTrangChu = new controller.CustomLabel();
        clbGiaoDich = new controller.CustomLabel();
        clbHoaDon = new controller.CustomLabel();
        clbDoiHang = new controller.CustomLabel();
        clbNhanVien = new controller.CustomLabel();
        clbKhachHang = new controller.CustomLabel();
        clbNhaCungCap = new controller.CustomLabel();
        clbSanPham = new controller.CustomLabel();
        clbChiTietSanPham = new controller.CustomLabel();
        clbNhapHang = new controller.CustomLabel();
        clbKhuyenMai = new controller.CustomLabel();
        clbThongKe = new controller.CustomLabel();
        clbThoat = new controller.CustomLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(250, 810));
        setMinimumSize(new java.awt.Dimension(250, 810));
        setPreferredSize(new java.awt.Dimension(250, 810));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logox75.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 50));

        clbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/TrangChu_24x.jpg"))); // NOI18N
        clbTrangChu.setText("    Trang chủ             ");
        add(clbTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 55));

        clbGiaoDich.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbGiaoDich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/GiaoDich_24x.jpg"))); // NOI18N
        clbGiaoDich.setText("    Giao dịch         ");
        add(clbGiaoDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 135, 250, 55));

        clbHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HoaDon_24x.jpg"))); // NOI18N
        clbHoaDon.setText("    Hóa đơn          ");
        add(clbHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 55));

        clbDoiHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbDoiHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/DoiHang_24x.jpg"))); // NOI18N
        clbDoiHang.setText("     Đổi hàng         ");
        clbDoiHang.setAutoscrolls(true);
        add(clbDoiHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 250, 55));

        clbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhanVien_24x.jpg"))); // NOI18N
        clbNhanVien.setText("      Nhân viên       ");
        add(clbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 55));

        clbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/KhachHang_24x.png"))); // NOI18N
        clbKhachHang.setText("      Khách hàng     ");
        add(clbKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, 250, 55));

        clbNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhaCungCap_24x.jpg"))); // NOI18N
        clbNhaCungCap.setText("     Nhà cung cấp  ");
        add(clbNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 250, 55));

        clbSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SanPham_24x.jpg"))); // NOI18N
        clbSanPham.setText("     Sản phẩm         ");
        add(clbSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 465, 250, 55));

        clbChiTietSanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbChiTietSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ChiTietSanPham_24x.jpg"))); // NOI18N
        clbChiTietSanPham.setText("    Thuộc tính        ");
        add(clbChiTietSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 55));

        clbNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/NhapHang_24x.jpg"))); // NOI18N
        clbNhapHang.setText("     Nhập hàng        ");
        add(clbNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 575, 250, 55));

        clbKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/KhuyenMai_24x.jpg"))); // NOI18N
        clbKhuyenMai.setText("     Khuyến mãi      ");
        add(clbKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 250, 55));

        clbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ThongKe_24x.jpg"))); // NOI18N
        clbThongKe.setText("    Thống kê           ");
        clbThongKe.setToolTipText("");
        add(clbThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 685, 250, 55));

        clbThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Thoat_24x.jpg"))); // NOI18N
        clbThoat.setText("      Thoát               ");
        add(clbThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 250, 55));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controller.CustomLabel clbChiTietSanPham;
    private controller.CustomLabel clbDoiHang;
    private controller.CustomLabel clbGiaoDich;
    private controller.CustomLabel clbHoaDon;
    private controller.CustomLabel clbKhachHang;
    private controller.CustomLabel clbKhuyenMai;
    private controller.CustomLabel clbNhaCungCap;
    private controller.CustomLabel clbNhanVien;
    private controller.CustomLabel clbNhapHang;
    private controller.CustomLabel clbSanPham;
    private controller.CustomLabel clbThoat;
    private controller.CustomLabel clbThongKe;
    private controller.CustomLabel clbTrangChu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
