/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import util.NhanVienDAO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import util.Auth;
import util.XFile;

/**
 *
 * @author Hi There
 */
public class chuyenServer extends javax.swing.JPanel {

    /**
     * Creates new form DangNhap1
     */
    public chuyenServer() {
        initComponents();
    }
    
public void chuyenDoi() {
    String sever = txtSever.getText();
    String database = txtDatabase.getText();

    // Chuyển đổi và tạo chuỗi cần lưu vào file
    String contentToSave = "Sever: " + sever + "\nDatabase: " + database;
    XFile xf = new XFile();
    // Lưu chuỗi vào file   
    xf.saveToFile("sever.txt", contentToSave);
    JOptionPane.showMessageDialog(this, "Đã lưu sever và database vào file sever.txt");
}
    public void changeTab(JPanel pnl) {
        removeAll();
        revalidate();
        repaint();
        setLayout(new AbsoluteLayout());
        add(pnl, new AbsoluteConstraints(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQuayLai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSever = new javax.swing.JTextField();
        btnChuyenDoi = new javax.swing.JButton();
        txtDatabase = new javax.swing.JTextField();

        setBackground(new java.awt.Color(254, 220, 197));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 530, 470));

        jPanel2.setBackground(new java.awt.Color(254, 230, 214));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Chuyển Sever");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Sever:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 101, -1));

        lblQuayLai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblQuayLai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayLai.setText("Quay lại đăng nhập");
        lblQuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayLaiMouseClicked(evt);
            }
        });
        jPanel2.add(lblQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Database:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, -1));

        txtSever.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(txtSever, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 340, 40));

        btnChuyenDoi.setBackground(new java.awt.Color(80, 199, 255));
        btnChuyenDoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChuyenDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenDoi.setText("Chuyển đổi");
        btnChuyenDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnChuyenDoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 150, 40));

        txtDatabase.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(txtDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 340, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 420, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnChuyenDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDoiActionPerformed
        chuyenDoi();
    }//GEN-LAST:event_btnChuyenDoiActionPerformed

    private void lblQuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayLaiMouseClicked
        new login().show();
    }//GEN-LAST:event_lblQuayLaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblQuayLai;
    private javax.swing.JTextField txtDatabase;
    private javax.swing.JTextField txtSever;
    // End of variables declaration//GEN-END:variables
}
