/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import util.NhanVienDAO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import util.Encode;

/**
 *
 * @author Hi There
 */
public class DoiMatKhau extends javax.swing.JPanel {

    public String email;
    
    public void setEmail(String email){
       this.email = email;
    }
    
    public DoiMatKhau() {
        initComponents();
    }

    public void changeTab(JPanel pnl) {
        removeAll();
        revalidate();
        repaint();
        setLayout(new AbsoluteLayout());
        add(pnl, new AbsoluteConstraints(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDangNhap = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQuayVe = new javax.swing.JLabel();
        lblMat2 = new javax.swing.JLabel();
        lblMat1 = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();

        pnlDangNhap.setBackground(new java.awt.Color(254, 220, 197));
        pnlDangNhap.setMaximumSize(new java.awt.Dimension(1280, 730));
        pnlDangNhap.setMinimumSize(new java.awt.Dimension(1280, 730));
        pnlDangNhap.setPreferredSize(new java.awt.Dimension(1280, 730));
        pnlDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinh (2).png"))); // NOI18N
        pnlDangNhap.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 440));

        jPanel2.setBackground(new java.awt.Color(254, 230, 214));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("Đổi mật khẩu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 189, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Mật khẩu mới:(*)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 120, -1));

        lblQuayVe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayVe.setText("Quay về đăng nhập");
        lblQuayVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayVeMouseClicked(evt);
            }
        });
        jPanel2.add(lblQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, -1));

        lblMat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mat.png"))); // NOI18N
        lblMat2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMat2MouseClicked(evt);
            }
        });
        jPanel2.add(lblMat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        lblMat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mat.png"))); // NOI18N
        lblMat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMat1MouseClicked(evt);
            }
        });
        jPanel2.add(lblMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        txtMatKhauMoi.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jPanel2.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 310, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu:(*)");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, -1));

        txtNhapLaiMatKhau.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtNhapLaiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNhapLaiMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(txtNhapLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 310, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mat.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        btnXacNhan.setBackground(new java.awt.Color(80, 199, 255));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Đổi mật khẩu");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel2.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        pnlDangNhap.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 430, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    boolean matkhau = true;
    NhanVienDAO nvDAO = new NhanVienDAO();
    Encode en = new Encode();

    private void doiMatKhau() {
        String matKhauMoi = new String(txtMatKhauMoi.getText());
        String NhaplaiMatKhau = new String(txtNhapLaiMatKhau.getText());
        if (!matKhauMoi.equals(NhaplaiMatKhau)) {
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không khớp!");
        } else {
            try {
                model.NhanVien nv = nvDAO.selectByEmail(email);
                nv.setMatKhau(en.hashPassword(matKhauMoi));
                nvDAO.update(nv);
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
                new login().show();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu không thành công!");
            }
        }
    }

    private void lblMat2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMat2MouseClicked
        if (matkhau == true) {
            txtMatKhauMoi.setEchoChar((char) 0);
            lblMat2.setIcon(new ImageIcon("src\\icon\\Mat.png"));
            matkhau = false;
        } else {
            txtMatKhauMoi.setEchoChar('*');
            lblMat2.setIcon(new ImageIcon("src\\icon\\MatDong.png"));
            matkhau = true;
        }
    }//GEN-LAST:event_lblMat2MouseClicked

    private void lblMat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMat1MouseClicked
        if (matkhau == true) {
            txtMatKhauMoi.setEchoChar((char) 0);
            lblMat1.setIcon(new ImageIcon("src\\icon\\Mat.png"));
            matkhau = false;
        } else {
            txtMatKhauMoi.setEchoChar('*');
            lblMat1.setIcon(new ImageIcon("src\\icon\\MatDong.png"));
            matkhau = true;
        }
    }//GEN-LAST:event_lblMat1MouseClicked

    private void txtNhapLaiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNhapLaiMatKhauMouseClicked

    }//GEN-LAST:event_txtNhapLaiMatKhauMouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void lblQuayVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayVeMouseClicked
        new login().show();
    }//GEN-LAST:event_lblQuayVeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMat1;
    private javax.swing.JLabel lblMat2;
    private javax.swing.JLabel lblQuayVe;
    private javax.swing.JPanel pnlDangNhap;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables

}
